
rule nextclade__to_html:
    input:
        "test1_nextclade.tsv",
    output:
        "nextclade.html",
    log:
        "logs/nextclade__to_html.log",
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/nextclade/to_html"
