rule picard__mark_duplicates:
    input:
        bam="test_sample.bam",
        bai="test_sample.bam.bai",
    output:
        bam="deduplicated.bam",
        stat="deduplicated.stats",
    log:
        "logs/picard__mark_duplicates.log",
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/picard/markduplicates"
