rule bowtie2__prepare_index:
    input:
        reference="test.fa",
    output:
        idx=multiext(
            "bowtie2_index/genome",
            ".1.bt2",
            ".2.bt2",
            ".3.bt2",
            ".4.bt2",
            ".rev.1.bt2",
            ".rev.2.bt2",
        ),
    params:
        prefix=lambda wildcards, output: output.idx[0][: -len(".1.bt2")],
    log:
        out="logs/bowtie2__prepare_index.log",
    threads: 2
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/bowtie2/index"
