rule cutadapt__trim_reads:
    input:
        r1="test_sample_R1.fastq.gz",
        r2="test_sample_R2.fastq.gz",
        fasta="adapters.fasta",
    output:
        r1="trimmed/test_sample_R1.fastq.gz",
        r2="trimmed/test_sample_R2.fastq.gz",
        report="trimmed/test_sample_cutadapt.json",
    params:
        anywhere_adapter="file:adapters.fasta",
        front_adapter="",
        regular_adapter="",
        overlap=10,
        error_rate=0.1,
        times=1,
        action="trim",
        minimum_length=0,
        quality_cutoff=0,
        head_cut="1:2",
        tail_cut="2:2",
    threads: 2
    log:
        "logs/cutadapt__trim_reads_paired.log",
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/cutadapt/paired"
