rule cutadapt__trim_reads_pe:
    input:
        ["test_sample_R1.fastq.gz", "test_sample_R2.fastq.gz"],
    output:
        r1="trimmed/test_sample_R1.fastq.gz",
        r2="trimmed/test_sample_R2.fastq.gz",
        report="trimmed/test_sample_cutadapt.json",
    params:
        extra="--anywhere file:adapters.fasta --max-n 3",
    threads: 2
    log:
        "logs/cutadapt__trim_reads_paired.log",
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/cutadapt/paired"
