rule fastuniq__deduplicate_reads_pe:
    input:
        r1="test_sample_R1.fastq.gz",
        r2="test_sample_R2.fastq.gz",
    output:
        r1="deduplicated/test_sample_R1.fastq.gz",
        r2="deduplicated/test_sample_R2.fastq.gz",
        unzipped_out_r1=temp("deduplicated/test_sample_R1.fastq"),
        unzipped_out_r2=temp("deduplicated/test_sample_R2.fastq"),
        pair_description=temp("deduplicated/test_sample.txt"),
    threads: 2
    log:
        "logs/fastuniq.log",
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/fastuniq/paired"
