rule ivar__call_variants:
    input:
        bam="test_sample.bam",
        bai="test_sample.bam.bai",
        ref="genome.fa",
    output:
        tsv="results/variants/test_sample.tsv",
    params:
        samtools_params="--no-BAQ -aa",
        ivar_params="-t 0.03",
    log:
        "logs/ivar__call_variants.log",
    wrapper:
        "https://github.com/xsitarcik/wrappers/raw/main/wrappers/ivar/variants"
